name: 'Thank You Supporter'
description: 'GROWTH HACK - Engage everyone that give a star to your project'
inputs:
  template:
    description: 'The template containing the content that need to be used'
    required: true
    default: './.github/template/thankyou-star.yaml'
  personal-github-token:
    description: 'The Github personal token used for creating issues on third party repo'
    required: true
    default: './.github/template/thankyou-template.yml'
  discord-webhook:
    description: 'The Webhook url of the your discord channel'
    required: true
    default: './.github/template/thankyou-star.yaml'
runs:
  using: 'node16'
  main: 'dist/index.cjs'
